### ISSUE TITLE
Comportamento estranho nas estatísticas 

### ISSUE THREAD

**Issue by jpvendramini** [jpvendramini/portal-rinha-backend#21]
Ao loggar em uma conta que não possui submissões, tanto a tabela quanto o gráfico entram em um loop:
![image](https://github.com/jpvendramini/portal-rinha-backend/assets/37249457/34462603-caa0-4238-8afe-369121c33ba2)
![image](https://github.com/jpvendramini/portal-rinha-backend/assets/37249457/dc25b631-3fe8-40a9-bac8-cdb74dc876a2)
Os resultados ficam encolhendo, voltam ao tamanho normal e repetem a ação.

**Comment by pablowinck** [comment]
Notei também que parou de aparecer o gráfico :-1: 
![image](https://github.com/jpvendramini/portal-rinha-backend/assets/70986781/a9e60101-2e92-42d1-bd02-3639969713f4)
