### ISSUE TITLE
Adicionar link do linkedin em toda div do contribuidor

### ISSUE THREAD

**Issue by pablowinck** [jpvendramini/portal-rinha-backend#29]
Hoje o link do linkedin está somente no nome do contribuidor, porém fica difícil entender tal ação.
Não acha que fica mto melhor se estivesse em toda div? Ex: deu a animação da cor, já fica disponível clicar e mandar pro linkedin?

**Comment by jpvendramini** [comment]
Acho uma solução interessante.
